name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 18:30 UTC daily
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Step with email 21f3002256@ds.study.iitm.ac.in
        run: echo "This step includes the email 21f3002256@ds.study.iitm.ac.in in its name."
      - name: Create a commit
        run: |
          echo "Daily commit by GitHub Actions" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit by GitHub Actions"
          git push
